import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hospice-cap-liability-reimbursement",
  "engine": "recovery",
  "title": "Hospice Cap Liability & Reimbursement",
  "shortTitle": "Hospice Cap Liability and Reimbursement",
  "tagline": "Forecast aggregate and inpatient cap exposure, validate beneficiary allocation, and reconcile repayment or reimbursement amounts.",
  "industry": "Hospice Financial Operations",
  "buyer": "Hospice providers and health systems",
  "uiPort": 4654,
  "apiPort": 5654,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Hospice Cap Liability & Reimbursement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements in one accountable workflow. Forecast aggregate and inpatient cap exposure, validate beneficiary allocation, and reconcile repayment or reimbursement amounts.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Hospice Cap Liability & Reimbursement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("election-benefit-registry","HCL01","Election benefit registry","Execute election benefit registry using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed election benefit registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Election benefit registry Reference","text","HCL01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("beneficiary-count-calculation","HCL02","Beneficiary count calculation","Execute beneficiary count calculation using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed beneficiary count calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Beneficiary count calculation Reference","text","HCL02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("service-day-ingestion","HCL03","Service-day ingestion","Execute service-day ingestion using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed service-day ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Service-day ingestion Reference","text","HCL03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("transfer-allocation","HCL04","Transfer allocation","Execute transfer allocation using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed transfer allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Transfer allocation Reference","text","HCL04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("live-discharge-treatment","HCL05","Live-discharge treatment","Execute live-discharge treatment using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed live-discharge treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Live-discharge treatment Reference","text","HCL05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("payment-ingestion","HCL06","Payment ingestion","Execute payment ingestion using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed payment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Payment ingestion Reference","text","HCL06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("aggregate-cap-calculation","HCL07","Aggregate cap calculation","Execute aggregate cap calculation using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed aggregate cap calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Aggregate cap calculation Reference","text","HCL07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("proportional-method","HCL08","Proportional method","Execute proportional method using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed proportional method decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Proportional method Reference","text","HCL08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("streamlined-method","HCL09","Streamlined method","Execute streamlined method using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed streamlined method decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Streamlined method Reference","text","HCL09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("inpatient-day-ratio","HCL10","Inpatient day ratio","Execute inpatient day ratio using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed inpatient day ratio decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Inpatient day ratio Reference","text","HCL10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("sequestration-treatment","HCL11","Sequestration treatment","Execute sequestration treatment using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed sequestration treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Sequestration treatment Reference","text","HCL11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("notice-reconciliation","HCL12","Notice reconciliation","Execute notice reconciliation using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed notice reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Notice reconciliation Reference","text","HCL12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("liability-forecast","HCL13","Liability forecast","Execute liability forecast using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed liability forecast decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Liability forecast Reference","text","HCL13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("settlement-payment-workflow","HCL14","Settlement payment workflow","Execute settlement payment workflow using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed settlement payment workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Settlement payment workflow Reference","text","HCL14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]}),
feature("provider-cap-analytics","HCL15","Provider cap analytics","Execute provider cap analytics using beneficiary elections, service days, payments, transfers, live discharges, inpatient days, sequestration, cap calculations, notices, and settlements.","Produce a governed provider cap analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Cap Year","text","Provider / Cap Year · Standard Case"],["caseReference","Provider cap analytics Reference","text","HCL15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",658750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",797088],["domainDriver","Cap Method","select","Streamlined",["Streamlined","Proportional","Inpatient cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Election benefit registry case","Beneficiary count calculation case","Service-day ingestion case","Transfer allocation case","Live-discharge treatment case"]})
]);
